apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.GOOGLE_CLOUD_PROJECT | quote }}
type: Opaque
data:
  {{- if and .Values.credentials.enabled .Values.credentials.localFilePath .Values.credentials.containerFileName }}
  {{ .Values.credentials.containerFileName }}: {{ .Files.Get .Values.credentials.localFilePath | b64enc }}
  {{- end }}
