{{- if and .Values.credentials (hasKey .Values.credentials "enabled") .Values.credentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: chatbot-rag-app-credentials

type: Opaque
data:
{{- if and .Values.credentials.localFilePath .Values.credentials.containerFileName }}
  {{ .Values.credentials.containerFileName }}: {{ .Files.Get .Values.credentials.localFilePath | b64enc }}
{{- end }}
{{- end }}
